const CONFIG = {
    introTitle: 'Bello Vợ Êu!!!',
    introDesc: `Anh hỏi nhớ trả lời thật lòng nhé`,
    btnIntro: 'Ô Cơ',
    title: 'Em có yêu anh nhiều nhiều hong? 😙',
    desc: 'Em không trả lời hoặc tắt trang là đồng ý nhé',
    btnYes: 'yêu lắm luôn á <3',
    btnNo: 'dẹp đê!!!',
    question:'Sao yêu anh dị :D',
    btnReply: 'Gửi qua đây nèo <3',
    reply: 'Tại vì em yêu anh',
    mess: 'Ahihi Anh biết mà 🥰',
    messDesc: 'Giờ còn chờ gì nữa nhấc mông lên và gọi cho anh nào :D',
    btnAccept: 'Ố Cơ',
}
